apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: wiki
  name: wiki
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ghcr.io/requarks/wiki:2
      generation: null
      importPolicy: {}
      name: "2"
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
